### ISSUE TITLE
self_def.yolov3_voc

### ISSUE THREAD

**Issue by GoodMan-1** [xlsjdjdk/Ship-Detection-based-on-YOLOv3-and-KV260#1]
Hi, in [dpu_yolov3_voc.ipynb](https://github.com/xlsjdjdk/Ship-Detection-based-on-YOLOv3-and-KV260/blob/master/yolov3_dpu/dpu_yolov3_voc.ipynb) there is "from self_ def. yolov3_ VOC import *". I don't know where "self_def" file is. Could you tell me where this file is? Thank you very much.

**Comment by xlsjdjdk** [comment]
Sorry for not uploading the file. It has been fixed and can be found under [yolov3_dpu](https://github.com/xlsjdjdk/Ship-Detection-based-on-YOLOv3-and-KV260/tree/master/yolov3_dpu). Any questions about vitis-ai workflow can submit an issue to me(*^_^*)
